### ISSUE TITLE
Why does it depend on Clang?

### ISSUE THREAD

**Issue by notdanilo** [jkvargas/russimp#17]

**Comment by jkvargas** [comment]
It does need if you want to compile Assimp by yourself.
Otherwise you're good to go without it :)

**Comment by notdanilo** [comment]
@jkvargas something is failing for me.

Adding this should be enough to compile it as a dependency, right?
```toml
[dependencies]
russimp = "0.2.3"
```

At first I got this error:
```
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (i
nvalid: [])"', C:\Users\dangu\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.57.0\src/lib.rs:1975:31
```

And this is what I am facing after installing https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/LLVM-12.0.1-win64.exe
```
  wrapper.h:1:10: fatal error: 'assimp/cimport.h' file not found
  wrapper.h:1:10: fatal error: 'assimp/cimport.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', C:\Users\dangu\.cargo\registry\src\github.com-1ecc6299db9ec823\russimp-sys-0.2.4\build.rs:31:10
```

**Comment by jkvargas** [comment]
So, windows is a problem hehe.
This package was mainly developed on linux.
There is a branch which I am trying a windows build without success so far.
I am trying to use vcpkg to build it.

**Comment by notdanilo** [comment]
@jkvargas yeah, I just realized it: https://github.com/jkvargas/russimp/runs/3645140896?check_suite_focus=true
Where can I connect to you via an instant messaging?

**Comment by notdanilo** [comment]
If you want me to help you with this, drop me a message because I would like to understand the issue.
Here is my Telegram profile: https://www.temporary-url.com/EB8687

**Comment by jkvargas** [comment]
hey mate,
So, I don't use telegram. 
Do you have discord, signal, facebook maybe?

**Comment by notdanilo** [comment]
@jkvargas sure, it's https://www.facebook.com/notdanilo
