### ISSUE TITLE
Typo in postprocessing enum variant

### ISSUE THREAD

**Issue by davidepi** [jkvargas/russimp#20]
In the `PostProcessing` enum, in the [scene.rs file at line 302](https://github.com/jkvargas/russimp/blob/master/src/scene.rs#L302) the variant `GenerateUVCoords` is mispelled as `GenenerateUVCoords`

Unfortunately you just released 1.0 and renaming the variant is a breaking change. Probably deprecating the current one and adding a new variant with the correct name is the best option right now.

**Comment by jkvargas** [comment]
Thanks for letting me know, mate.
Pipelines are executing right now for version 1.0.1 with the fix.
:)

**Comment by jkvargas** [comment]
let me know if you have any problems with 1.0.1

**Comment by davidepi** [comment]
Everything was fine, tried both on linux with assimp built from source and on macOS with the brew version.

Thanks!
