### ISSUE TITLE
docs.rs build is broken

### ISSUE THREAD

**Issue by JoeOsborn** [jkvargas/russimp#24]
Because russimp needs to either have assimp installed or use russimp-sys’s prebuilt feature, docs.rs builds have been busted for some time as they don’t allow network access during builds.

I think crates like z3 solve this by adding their dependency as a submodule and using bindgen on the headers in the submodule.

**Comment by jkvargas** [comment]
hey mate,
I will take a look as soon as I can, I am moving so I am kinda busy these last days.
If you find some free time yourself feel free to send another commit =)
