### ISSUE TITLE
failed to run custom build command for `russimp-sys v1.0.3`

### ISSUE THREAD

**Issue by Snowiiii** [jkvargas/russimp#41]
Caused by:
  process didn't exit successfully: `/home/snowii/Documents/Development/Rust/Vent-Engine/target/release/build/russimp-sys-797602f794b2476a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=RUSSIMP_PREBUILT
  Downloading https://github.com/jkvargas/russimp-sys/releases/download/v1.0.3/russimp-1.0.3-x86_64-pc-windows-gnu.tar.gz

  --- stderr
  thread 'main' panicked at 'Download Failed: Custom { kind: Other, error: "https://github.com/jkvargas/russimp-sys/releases/download/v1.0.3/russimp-1.0.3-x86_64-pc-windows-gnu.tar.gz: status code 404" }', /home/snowii/.cargo/registry/src/github.com-1ecc6299db9ec823/russimp-sys-1.0.3/build.rs:283:73
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

- Windows-gnu -

**Comment by jkvargas** [comment]
you're not able to download because that is not an available target
https://github.com/jkvargas/russimp-sys/releases/tag/v1.0.3

I am not familiar with windows, what exactly is windows-gnu?

**Comment by Snowiiii** [comment]
Windows-gnu is a toolchain that allows you to compile Windows executables on a Linux machine. As for Russimp, it's a unique crate that I've encountered while working with Rust. Despite using prebuilt libraries, I still have to compile it separately for Linux, Mac, and Windows platforms (https://github.com/Snowiiii/Vent-Engine/blob/master/.github/workflows/rust.yml#L26). To compile Russimp for Linux, you need to have GTK installed, while for Windows, I encountered the error mentioned above. This crate has been giving me some unexpected issues, unlike any other crates I've worked with.

**Comment by jkvargas** [comment]
Is the first time I am reading that someone needs GTK to compile russimp... How did you got to that conclusion?
You can take a look at https://github.com/jkvargas/russimp/blob/master/.github/workflows/russimp.yml if you want to see how russimp is built for linux.
I don't have windows on my side so I don't pay much attention to it but I do accept possible PRs for it.
I am sorry that you're having a hard time with the library.
