### ISSUE TITLE
AABB seems broken

### ISSUE THREAD

**Issue by virtualritz** [jkvargas/russimp#8]
I tried a simple example loading an OBJ.
The AABB is always zero (all coordinates of `min` & `max` are zero). Haven't dug into this, just documenting this.

**Comment by jkvargas** [comment]
hey dude,
can you share a simplest possible file with that issue?
would be nice to add a test to make sure that this will be working at the future.

**Comment by virtualritz** [comment]
Yeah, prepped my fork yesterday for that by adding `Scene::from_buffer()` so the input file can be included in the source. I hope I get to it before the weekend.

**Comment by virtualritz** [comment]
Everything is in the [`assimp-sys` branch of my `russimp` fork](https://github.com/virtualritz/russimp/tree/assimp-sys)

There is a [`bounding_box()` test in `scene.rs`](https://github.com/virtualritz/russimp/blob/e06da47d56a0b95aaf6dbf6c8d8183c76c843de2/src/scene.rs#L545-L574) that currently fails (demonstrates the issue with three lines of code).

**Comment by jkvargas** [comment]
hey dude,
so just to close this issue,

I made a small app here just to test this out directly from assimp.

`#include <assimp/Importer.hpp>      // C++ importer interface
#include <assimp/scene.h>           // Output data structure
#include <assimp/postprocess.h>     // Post processing flags
#include <string>
#include <iostream>

int main() {
    Assimp::Importer importer;

    std::string content = "o T\nv  1  1  1\nv  1 -1 -1\nv -1  1 -1\nv -1 -1  1\nf 1 2 3\nf 1 3 4\nf 1 4 2\nf 2 4 3\n";

    auto* scene = importer.ReadFileFromMemory(content.c_str(), content.length(), aiProcess_CalcTangentSpace       |
                                                                                 aiProcess_Triangulate            |
                                                                                 aiProcess_JoinIdenticalVertices  |
                                                                                 aiProcess_SortByPType);
    std::cout << "max_x: " << scene->mMeshes[0]->mAABB.mMax.x << std::endl;
    std::cout << "max_y: " << scene->mMeshes[0]->mAABB.mMax.y << std::endl;
    std::cout << "max_z: " << scene->mMeshes[0]->mAABB.mMax.z << std::endl;
    std::cout << "min_x: " << scene->mMeshes[0]->mAABB.mMin.x << std::endl;
    std::cout << "min_y: " << scene->mMeshes[0]->mAABB.mMin.y << std::endl;
    std::cout << "min_z: " << scene->mMeshes[0]->mAABB.mMin.z << std::endl;

    return 0;
}`

This is outputting:

max_x: 0
max_y: 0
max_z: 0
min_x: 0
min_y: 0
min_z: 0

I suppose that's an issue with them. =)
